### ISSUE TITLE
Using Service Manager at scale

### ISSUE THREAD

**Issue by ahawes-clarity** [pro-celigo/lib-netsuite-servicemgr#30]
I am migrating code from an older net framework app that processes large volumes of data and therefore needs to manage the connections carefully.

I am very interested in using your service manager but I want to ask what considerations have been made for managing the connections. I am using the Token Based Authentication. All calls are made from the context of the app and not any user contexts.

I know NetSuite has limitations based on licensing.

Should the client be implemented as a static or singleton or recreated per request/session etc? Our current app sets a number of client instances that can run concurrently but I am not sure if this is needed or not. We want to maximize throughput and will usually have multiple instances of the app running at the same time so ideally each instance of the app would only have one client connection.

Any thoughts you can provide about using service manager at scale would be very helpful.

Thanks

**Comment by sameera** [comment]
@ahawes-clarity
An instance of the `INetSuiteClient` is meant to be used with one NetSuite user. If the user is logged in to the app throughout the lifetime of the application, it would be advisable to use that instance as a singleton. However, note that the class itself doesn't guard against the possibility of hitting Concurrent Session errors in NetSuite. We used to enforce this in older versions of this library. However, once NetSuite change the concurrency limit to apply across account (instead of per user) for TBA, we no longer lock at a function level to avoid single inflight request per user.

I'm giving you the above answer because I wasn't clear on how your app behaved: you mentioned that it runs in a non-user context but you did also mention request/session. Is it that the app runs with a single NetSuite credential but accepts requests from multiple non-NetSuite users?

I'm not sure I have given you enough information to be useful. If I can understand overall model of how the app behaves, I could probably provide more guidance.

**Comment by ahawes-clarity** [comment]
Thanks @sameera, the app is an integration app. It is responsible for taking data from other systems and injecting it into NetSuite and/or looking up data in NetSuite to be uses in other systems. So, in all these cases there is one integration "user" account that makes all the requests. Each logical operation on the integration side may involve one or more NetSuite requests.

I did notice in the Unit Test that you had a test using Poly with retries. That is similar to what the existing application uses (without Poly). We currently have an integrations concurrency limit of 15. So, if I understand what you have said about the Service Manager, it is not doing anything fancy under the hood to manage or pool connections and/or manage concurrency. That means that one instance of INetSuiteClient is one connection to NetSuite and if I need to manage concurrency I need to manage the number and life-cycle of the INetSuiteClient instances. Is that correct?

Does the INetSuiteClient have a way to detect when it is no longer valid (been rejected by NetSuite)? Or do I need to continue to parse responses to know when I need to create a new INetSuiteClient?

Another issue that I have that is somewhat out of scope of my original question is that I need to manage the concurrency when multiple instance of the app may be running in different systems. I mention this in case you have any experience with this that you can share. We are using Azure Functions which can scale up to multiple instances but that also means we may have multiple instances of the app running. If I set each instance to only have one connection to NetSuite then I can't take advantage of the 15 concurrency limit I have. If I let each instance of the app use multiple NetSuite connections then I risk hitting my concurrency limit in aggregate. One potential solution is to not let the app hold on to connections but I am worried that the overhead of reconnecting all the time will be an issue. Thought?

**Comment by sameera** [comment]
@ahawes-clarity
> That means that one instance of INetSuiteClient is one connection to NetSuite
Not quite, but it does makes it cleaner to think of it that way for your use case (I'll explain below)

> I need to manage concurrency I need to manage the number and life-cycle of the INetSuiteClient instances. Is that correct?
As above, not exactly: But, it does make it easier to model if you approach it that way.

First, I'm making a major assumption: You are using Token Based Authentication (not username/password). In order for your to benefit from account level concurrency, you need to be using TBA - otherwise, you are still limited to one concurrent request per user.

Now, INetSuiteClient doesn't hold a persistent connection or session with NetSuite. It is merely a proxy class that is configured to call a NetSuite Webservice function. So, you can have a single instance of it and call it's `addList` method (for example) 15 times concurrently without running in to the NS limit. However, that would require you to somehow ensure that you don't make more than 15 calls concurrently and wait till one is done before calling the 16th.

If instead, you do model it as you said, instantiating 15 INetSuiteClients and putting them in a blocking queue. Then when you need to make a request, dequeue one execute the command, wait for it to be done and return it to the queue. This is exactly what we used to do in our older library:
https://github.com/celigo/netsuite-service-manager-dotnet/blob/master/ServiceManager/NetSuiteServicePoolManager.cs

> Does the INetSuiteClient have a way to detect when it is no longer valid (been rejected by NetSuite)?
Since the client doesn't hold a persistent connection or session; it is valid until such time the TBA tokens are invalidated (which  has to be done explicitly from the NetSuite UI). If the tokens are invalidated, you'll start getting an invalid credentials error which you'll need to look out for.

**Comment by sameera** [comment]
When running in an Azure Function, I would recommend that you do not use the above approach (pool of INetSuiteClients) and stick with one instance and making sure that instance doesn't make concurrent requests to NetSuite.
Instead, set the concurrency limit of Azure Function to 15*, so that at a given time, there can only be 15 clients connected to NetSuite. 
Important thing to note here is that no matter how much your code can scale, your real bottleneck is hitting NetSuite. You might be able to optimize this by keeping the code that calls NetSuite in one Az Function (which will have a concurrency limit of 15) and keeping the preprocessing code in another set of lambdas that can scale beyond that. 

* We use AWS and I'm not aware whether setting such concurrency limits are possible in Azure. It is possible in AWS.

**Comment by ahawes-clarity** [comment]
Thanks for all sharing all your wisdom and code.

My challenge is that I also have one shared NetSuite integration code base that I had hoped would work in a Azure Functions scenario and also in a standard web app scenario. When I refactor I will need to add connection pooling as an optional bit so that by config I can enable or disable and also set the number of concurrent connections. And none if this is to mention that the customer we are writing the code for uses other NetSuite integrations as well. ( one from Celigo ;) )

**Comment by sameera** [comment]
Noted :)
Yes, dealing with concurrency across the account would be a challenge and we'll always need to implement retry mechanisms to counter that. This is where Polly could come in handy.
Anyways, hope all of this was helpful. Feel free t reach out if you have similar questions.
